### GET ALL ITEMS
GET http://localhost:8080/data/inventory HTTP/1.1

###GET SINGLE ITEM
# GET http://localhost:8080/items/2 HTTP/1.1

### ADD ITEM
POST http://localhost:8080/data/inventory HTTP/1.1
Content-Type: application/json

{
    "itemname": "Spandals SUPER-XXXL",
    "class": "Footware",
    "price": 10,
    "quantity": 1
}

### DELETE ITEM
DELETE http://localhost:8080/items/3 HTTP/1.1

### UPDATE ITEM
PUT http://localhost:8080/items/2 HTTP/1.1
Content-Type: application/json

{
    "name": "Updated Item"
}